# spring.application.name=digital-banking-system
# server.port=8000
# spring.datasource.url=jdbc:mysql://localhost:3306/bms
# spring.datasource.username=root
# spring.datasource.password=root@2026
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# jwt.secret=ThisIsMySuperSecretKeyForBankingManagementSystem
# jwt.expiration=3600000

spring.application.name=digital-banking-system
server.port=${PORT:8000}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root@2026}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET:ThisIsMySuperSecretKeyForBankingManagementSystem123456789}
jwt.expiration=3600000